site_name: Richard Shan
nav:
  - Home: index.md
  # - Coding Projects: coding.md
  - About: about.md
  # - Fab Academy:
  #   - Pre-Fab:
  #     - Storage Box: fab/cardboardBox.md
  #     - Tiny Arcade: arcade.md
  #     - Flashing Glasses: glasses.md
  # - Macro Project: macroProj.md
theme: readthedocs



